version: '3.5'

services:

  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
    ports:
      - 5432:5432
    volumes:
      - $(shell pwd)/schema.sql:/docker-entrypoint-initdb.d/schema.sql